package view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;;

public class Home extends javax.swing.JFrame {
    private int oper;
    
    DefaultTableModel dtmParticiones = new DefaultTableModel();

    public Home() {
        initComponents();
        initTabla();
        
        ImageIcon img = new ImageIcon(getClass().getResource("../images/logo.png"));
        this.setIconImage(img.getImage());
    }
    
    private void initTabla(){
        tblParticiones.getTableHeader().setFont(new Font("Arial Narrow", Font.BOLD, 18));
        tblParticiones.getTableHeader().setOpaque(false);
        tblParticiones.setRowHeight(45);
        tblParticiones.getColumnModel().getColumn(0).setPreferredWidth(10);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tblParticiones.setDefaultRenderer(tblParticiones.getColumnClass(0), centerRenderer);
        
        ((DefaultTableCellRenderer)tblParticiones.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
        txtInstrucciones.setText("1. Seleccione la función que desea utilizar, indicando el signo." +
                "\n\n2. Intruduzca el valor de la constante en la función."+
                "\n\n3. Indique los límites superior e inferior de la integral."+
                "\n\n4. Indique el valor de 'n' (si aplicaa)."+
                "\n\n5. Seleccione el método numérico.");
        txtInstrucciones.setEditable(false);
        txtInstrucciones.setCaretPosition(0);
        
    }
    
    private void setModelo(String fx){
        String[] titulo = {"#", "X", "F(x)=" + fx, "Resultado"};
        dtmParticiones.setRowCount(0);
        dtmParticiones.setColumnIdentifiers(titulo);
        tblParticiones.setModel(dtmParticiones);
        initTabla();
    }
    
    private void setParticion(int i, String x, String fx, String res){
        Object[] particion = new Object[dtmParticiones.getColumnCount()];
        
        particion[0] = i;
        particion[1] = x;
        particion[2] = fx;
        particion[3] = res;
        
        dtmParticiones.addRow(particion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTrapzoidal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSimpsonAbto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBoole = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSimpson3_8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnSimpson1_3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRaiz = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtVarRaiz = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        btnSignoRaiz = new javax.swing.JToggleButton();
        btnCargarRaiz = new javax.swing.JButton();
        btnRaiz1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtVarLog = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        btnSignoLog = new javax.swing.JToggleButton();
        btnCargarLog = new javax.swing.JButton();
        btnLn = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        txtVarLn = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        btnSignoLn = new javax.swing.JToggleButton();
        btnCargarLn = new javax.swing.JButton();
        btnExp = new javax.swing.JPanel();
        txtVarExp = new javax.swing.JTextField();
        btnCargarExp = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtB = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFx = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        lblDelta = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblDelta1 = new javax.swing.JLabel();
        lblMetodo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParticiones = new javax.swing.JTable();
        txtSumatoria = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInstrucciones = new javax.swing.JTextArea();
        btnGrafica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Infinity - Aplicación de Métodos Numéricos");
        setResizable(false);

        bg.setBackground(new java.awt.Color(235, 245, 251));
        bg.setFocusable(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(93, 173, 226));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-1.png"))); // NOI18N

        btnTrapzoidal.setBackground(new java.awt.Color(93, 173, 226));
        btnTrapzoidal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrapzoidal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrapzoidalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrapzoidalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrapzoidalMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/math-1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Trapezoidal");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Método");

        javax.swing.GroupLayout btnTrapzoidalLayout = new javax.swing.GroupLayout(btnTrapzoidal);
        btnTrapzoidal.setLayout(btnTrapzoidalLayout);
        btnTrapzoidalLayout.setHorizontalGroup(
            btnTrapzoidalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTrapzoidalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnTrapzoidalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnTrapzoidalLayout.setVerticalGroup(
            btnTrapzoidalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTrapzoidalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnTrapzoidalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnTrapzoidalLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSimpsonAbto.setBackground(new java.awt.Color(93, 173, 226));
        btnSimpsonAbto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpsonAbto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpsonAbtoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpsonAbtoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpsonAbtoMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/math-5.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Simpson Abierto");

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Método");

        javax.swing.GroupLayout btnSimpsonAbtoLayout = new javax.swing.GroupLayout(btnSimpsonAbto);
        btnSimpsonAbto.setLayout(btnSimpsonAbtoLayout);
        btnSimpsonAbtoLayout.setHorizontalGroup(
            btnSimpsonAbtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimpsonAbtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnSimpsonAbtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSimpsonAbtoLayout.setVerticalGroup(
            btnSimpsonAbtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimpsonAbtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSimpsonAbtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnSimpsonAbtoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBoole.setBackground(new java.awt.Color(93, 173, 226));
        btnBoole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBoole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBooleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBooleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBooleMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/math-2.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jorge Boole");

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Método");

        javax.swing.GroupLayout btnBooleLayout = new javax.swing.GroupLayout(btnBoole);
        btnBoole.setLayout(btnBooleLayout);
        btnBooleLayout.setHorizontalGroup(
            btnBooleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBooleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnBooleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBooleLayout.setVerticalGroup(
            btnBooleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBooleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnBooleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnBooleLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSimpson3_8.setBackground(new java.awt.Color(93, 173, 226));
        btnSimpson3_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpson3_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpson3_8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpson3_8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpson3_8MouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/math-3.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("T. Simpson 3/8");

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Método");

        javax.swing.GroupLayout btnSimpson3_8Layout = new javax.swing.GroupLayout(btnSimpson3_8);
        btnSimpson3_8.setLayout(btnSimpson3_8Layout);
        btnSimpson3_8Layout.setHorizontalGroup(
            btnSimpson3_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimpson3_8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnSimpson3_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSimpson3_8Layout.setVerticalGroup(
            btnSimpson3_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimpson3_8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSimpson3_8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnSimpson3_8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSimpson1_3.setBackground(new java.awt.Color(93, 173, 226));
        btnSimpson1_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpson1_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpson1_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpson1_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpson1_3MouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/math-4.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial Narrow", 1, 28)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("T. Simpson 1/3");

        jLabel17.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Método");

        javax.swing.GroupLayout btnSimpson1_3Layout = new javax.swing.GroupLayout(btnSimpson1_3);
        btnSimpson1_3.setLayout(btnSimpson1_3Layout);
        btnSimpson1_3Layout.setHorizontalGroup(
            btnSimpson1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimpson1_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnSimpson1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSimpson1_3Layout.setVerticalGroup(
            btnSimpson1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSimpson1_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnSimpson1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnSimpson1_3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBoole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrapzoidal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpson3_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpson1_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpsonAbto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addGap(39, 39, 39)
                .addComponent(btnTrapzoidal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBoole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpson3_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpson1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpsonAbto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 770));

        jPanel2.setBackground(new java.awt.Color(46, 134, 193));

        btnRaiz.setBackground(new java.awt.Color(46, 134, 193));
        btnRaiz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRaiz.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnRaizMouseDragged(evt);
            }
        });
        btnRaiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRaizMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("√(x");

        txtVarRaiz.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        txtVarRaiz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVarRaiz.setText("0");

        jLabel38.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText(")");

        btnSignoRaiz.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnSignoRaiz.setSelected(true);
        btnSignoRaiz.setText("?");
        btnSignoRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoRaizActionPerformed(evt);
            }
        });

        btnCargarRaiz.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCargarRaiz.setText("Cargar la Función");
        btnCargarRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarRaizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnRaizLayout = new javax.swing.GroupLayout(btnRaiz);
        btnRaiz.setLayout(btnRaizLayout);
        btnRaizLayout.setHorizontalGroup(
            btnRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRaizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnRaizLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignoRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVarRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        btnRaizLayout.setVerticalGroup(
            btnRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRaizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtVarRaiz)
                        .addGroup(btnRaizLayout.createSequentialGroup()
                            .addGroup(btnRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSignoRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1)))
                    .addComponent(jLabel38))
                .addGap(13, 13, 13)
                .addComponent(btnCargarRaiz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRaiz1.setBackground(new java.awt.Color(46, 134, 193));
        btnRaiz1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRaiz1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRaiz1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnRaiz1MouseDragged(evt);
            }
        });
        btnRaiz1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRaiz1MouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Log(x");

        txtVarLog.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        txtVarLog.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVarLog.setText("0");

        jLabel39.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(")");

        btnSignoLog.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnSignoLog.setSelected(true);
        btnSignoLog.setText("?");
        btnSignoLog.setToolTipText("Seleccione el signo");
        btnSignoLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoLogActionPerformed(evt);
            }
        });

        btnCargarLog.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCargarLog.setText("Cargar la Función");
        btnCargarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnRaiz1Layout = new javax.swing.GroupLayout(btnRaiz1);
        btnRaiz1.setLayout(btnRaiz1Layout);
        btnRaiz1Layout.setHorizontalGroup(
            btnRaiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRaiz1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnRaiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnRaiz1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignoLog, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVarLog, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        btnRaiz1Layout.setVerticalGroup(
            btnRaiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRaiz1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnRaiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnRaiz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtVarLog)
                        .addGroup(btnRaiz1Layout.createSequentialGroup()
                            .addComponent(btnSignoLog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addComponent(jLabel39)
                    .addComponent(jLabel23))
                .addGap(13, 13, 13)
                .addComponent(btnCargarLog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLn.setBackground(new java.awt.Color(46, 134, 193));
        btnLn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnLnMouseDragged(evt);
            }
        });
        btnLn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLnMouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Ln(x");

        txtVarLn.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        txtVarLn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVarLn.setText("0");

        jLabel44.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText(")");

        btnSignoLn.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnSignoLn.setSelected(true);
        btnSignoLn.setText("?");
        btnSignoLn.setToolTipText("Seleccione el signo");
        btnSignoLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoLnActionPerformed(evt);
            }
        });

        btnCargarLn.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCargarLn.setText("Cargar la Función");
        btnCargarLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarLnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnLnLayout = new javax.swing.GroupLayout(btnLn);
        btnLn.setLayout(btnLnLayout);
        btnLnLayout.setHorizontalGroup(
            btnLnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargarLn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnLnLayout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignoLn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVarLn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        btnLnLayout.setVerticalGroup(
            btnLnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnLnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtVarLn)
                        .addGroup(btnLnLayout.createSequentialGroup()
                            .addComponent(btnSignoLn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addComponent(jLabel44)
                    .addComponent(jLabel43))
                .addGap(13, 13, 13)
                .addComponent(btnCargarLn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExp.setBackground(new java.awt.Color(46, 134, 193));
        btnExp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btnExpMouseDragged(evt);
            }
        });
        btnExp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExpMouseClicked(evt);
            }
        });

        txtVarExp.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        txtVarExp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVarExp.setText("0");
        txtVarExp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVarExpFocusGained(evt);
            }
        });

        btnCargarExp.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCargarExp.setText("Cargar la Función");
        btnCargarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarExpActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("x");

        javax.swing.GroupLayout btnExpLayout = new javax.swing.GroupLayout(btnExp);
        btnExp.setLayout(btnExpLayout);
        btnExpLayout.setHorizontalGroup(
            btnExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargarExp, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btnExpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtVarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47)
                .addGap(67, 67, 67))
        );
        btnExpLayout.setVerticalGroup(
            btnExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExpLayout.createSequentialGroup()
                .addGroup(btnExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnExpLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtVarExp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarExp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRaiz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRaiz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 890, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 97, 140)));

        jLabel20.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(27, 79, 114));
        jLabel20.setText("Función:");

        txtB.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/integral.png"))); // NOI18N

        txtA.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(27, 79, 114));
        jLabel19.setText("f(x)=");

        txtFx.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        txtFx.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFx.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFx.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(27, 79, 114));
        jLabel21.setText("dx");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel20)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel19))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(txtFx, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txtFx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 550, 190));

        jPanel12.setBackground(new java.awt.Color(248, 248, 248));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 97, 140)));

        jLabel37.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(27, 79, 114));
        jLabel37.setText("n =");

        txtN.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        txtN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblDelta.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        lblDelta.setForeground(new java.awt.Color(27, 79, 114));
        lblDelta.setText("Δ =");

        lblArea.setFont(new java.awt.Font("Arial Narrow", 1, 34)); // NOI18N
        lblArea.setForeground(new java.awt.Color(212, 172, 13));
        lblArea.setText("0");

        jLabel40.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(27, 79, 114));
        jLabel40.setText("Area (u)");

        jLabel41.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel41.setText("2");

        lblDelta1.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        lblDelta1.setForeground(new java.awt.Color(27, 79, 114));
        lblDelta1.setText(":");

        lblMetodo.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        lblMetodo.setForeground(new java.awt.Color(212, 172, 13));
        lblMetodo.setText("Método");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArea)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel41)
                        .addGap(0, 0, 0)
                        .addComponent(lblDelta1))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDelta))
                    .addComponent(lblMetodo))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMetodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDelta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDelta1)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40))
                .addGap(0, 0, 0)
                .addComponent(lblArea))
        );

        bg.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 270, 190));

        tblParticiones.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        tblParticiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "X", "F(x)", "Resultado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblParticiones.setFocusable(false);
        tblParticiones.setRowHeight(45);
        tblParticiones.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblParticiones);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 550, 310));

        txtSumatoria.setEditable(false);
        txtSumatoria.setBackground(new java.awt.Color(46, 134, 193));
        txtSumatoria.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        txtSumatoria.setForeground(new java.awt.Color(255, 255, 255));
        txtSumatoria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSumatoria.setText("0");
        bg.add(txtSumatoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 690, 240, 40));

        jLabel42.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(27, 79, 114));
        jLabel42.setText("Sumatoria:");
        bg.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 690, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 97, 140)));

        jLabel24.setFont(new java.awt.Font("Arial Narrow", 1, 32)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(27, 79, 114));
        jLabel24.setText("Instrucciones:");

        txtInstrucciones.setEditable(false);
        txtInstrucciones.setColumns(20);
        txtInstrucciones.setFont(new java.awt.Font("Arial Narrow", 0, 22)); // NOI18N
        txtInstrucciones.setForeground(new java.awt.Color(102, 102, 102));
        txtInstrucciones.setLineWrap(true);
        txtInstrucciones.setRows(5);
        txtInstrucciones.setWrapStyleWord(true);
        txtInstrucciones.setAutoscrolls(false);
        jScrollPane3.setViewportView(txtInstrucciones);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(75, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 270, 370));

        btnGrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/math-7.png"))); // NOI18N
        btnGrafica.setToolTipText("Generar gráfica");
        btnGrafica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGraficaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGraficaMouseExited(evt);
            }
        });
        bg.add(btnGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 690, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrapzoidalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrapzoidalMouseEntered
        Color color = new Color(52, 152, 219);
        this.btnTrapzoidal.setBackground(color);
    }//GEN-LAST:event_btnTrapzoidalMouseEntered

    private void btnTrapzoidalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrapzoidalMouseExited
        Color color = new Color(93, 173, 226);
        this.btnTrapzoidal.setBackground(color);
    }//GEN-LAST:event_btnTrapzoidalMouseExited

    private void btnBooleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBooleMouseEntered
        Color color = new Color(52, 152, 219);
        this.btnBoole.setBackground(color);
    }//GEN-LAST:event_btnBooleMouseEntered

    private void btnSimpson3_8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpson3_8MouseEntered
        Color color = new Color(52, 152, 219);
        this.btnSimpson3_8.setBackground(color);
    }//GEN-LAST:event_btnSimpson3_8MouseEntered

    private void btnSimpson1_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpson1_3MouseEntered
        Color color = new Color(52, 152, 219);
        this.btnSimpson1_3.setBackground(color);
    }//GEN-LAST:event_btnSimpson1_3MouseEntered

    private void btnSimpsonAbtoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpsonAbtoMouseEntered
        Color color = new Color(52, 152, 219);
        this.btnSimpsonAbto.setBackground(color);
    }//GEN-LAST:event_btnSimpsonAbtoMouseEntered

    private void btnBooleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBooleMouseExited
        Color color = new Color(93, 173, 226);
        this.btnBoole.setBackground(color);
    }//GEN-LAST:event_btnBooleMouseExited

    private void btnSimpson3_8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpson3_8MouseExited
        Color color = new Color(93, 173, 226);
        this.btnSimpson3_8.setBackground(color);
    }//GEN-LAST:event_btnSimpson3_8MouseExited

    private void btnSimpson1_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpson1_3MouseExited
        Color color = new Color(93, 173, 226);
        this.btnSimpson1_3.setBackground(color);
    }//GEN-LAST:event_btnSimpson1_3MouseExited

    private void btnSimpsonAbtoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpsonAbtoMouseExited
        Color color = new Color(93, 173, 226);
        this.btnSimpsonAbto.setBackground(color);
    }//GEN-LAST:event_btnSimpsonAbtoMouseExited

    private void btnRaizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRaizMouseClicked

    }//GEN-LAST:event_btnRaizMouseClicked

    private void btnSignoRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoRaizActionPerformed
        if(btnSignoRaiz.isSelected()){
            btnSignoRaiz.setText("-");
        } else {
            btnSignoRaiz.setText("+");
        }
        
        txtVarRaiz.requestFocus();
        txtVarRaiz.selectAll();
    }//GEN-LAST:event_btnSignoRaizActionPerformed

    private void btnRaizMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRaizMouseDragged
    }//GEN-LAST:event_btnRaizMouseDragged

    private void btnCargarRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarRaizActionPerformed
        if(btnSignoRaiz.getText().equals("?")){
            JOptionPane.showMessageDialog(null, "Debe indicar un signo (+/-) para la función");
        } else {
            String signo = (btnSignoRaiz.isSelected())? "-" : "+";
            txtFx.setText("√(x" + signo + txtVarRaiz.getText() + ")");
            this.oper = 1;
        }
    }//GEN-LAST:event_btnCargarRaizActionPerformed

    private void btnTrapzoidalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrapzoidalMouseClicked
        if(txtA.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite interior");
            txtA.requestFocus();;
            txtA.selectAll();
        } else if(txtB.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite superior");
            txtB.requestFocus();;
            txtB.selectAll();
        } else if(txtN.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor par (n)");
            txtN.requestFocus();;
            txtN.selectAll();
        } else if(txtFx.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe seleccionar y cargar una función (vea la barra superior");
        } else {
        
            float delta = (Float.parseFloat(txtB.getText()) - Float.parseFloat(txtA.getText())) / Float.parseFloat(txtN.getText());
            lblMetodo.setText("Trapezoidal");
            lblDelta.setText("Δ = " + String.format("%,.2f", delta));
            String signo;

            setModelo(txtFx.getText());

            int n = Integer.parseInt(txtN.getText()) + 1;
            float x = Float.parseFloat(txtA.getText());
            double res = 0;
            float k = 0;
            double sumatoria = 0;
            String fx = "";
            String coef = "";

            System.out.println("Operacion: " + this.oper);

            for(int i=1; i<=n; i++){
                coef = "";

                switch(this.oper){
                    case 1:
                        signo = (btnSignoRaiz.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarRaiz.getText());
                        res = (signo.equals("+"))? Math.sqrt(x + k) : Math.sqrt(x - k);
                        fx = "√(" + String.format("%,.2f", x) + btnSignoRaiz.getText() + txtVarRaiz.getText() + ")";
                        break;

                    case 2:
                        signo = (btnSignoLog.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLog.getText());
                        res = (signo.equals("+"))? Math.log10(x + k) : Math.log10(x - k);
                        fx = "Log(" + String.format("%,.2f", x) + btnSignoLog.getText() + txtVarLog.getText() + ")";
                        break;

                    case 3:
                        signo = (btnSignoLn.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLn.getText());
                        res = (signo.equals("+"))? Math.log(x + k) : Math.log(x - k);
                        fx = "Ln(" + String.format("%,.2f", x) + btnSignoLn.getText() + txtVarLn.getText() + ")";
                        break;

                    case 4:
                        k = Float.parseFloat(txtVarExp.getText());
                        res = Math.pow(k, x);
                        fx = txtVarExp.getText() + "^" + String.format("%,.2f", x);
                        break;
                }
                
                if(Double.isNaN(res) || Double.isInfinite(res)) res = 0;

                if(i != 1 && i != n) {
                    res *= 2;
                    coef = "(2) ";
                }

                fx = coef + fx;

                setParticion(i, String.format("%,.2f", x), fx, String.format("%,.8f", res));

                sumatoria += res;
                System.out.println("X: " + x + " Res: " + res);
                x += delta;
            }

            System.out.println("Sumatoria: " + sumatoria);
            lblArea.setText(String.format("%,.8f", (delta / 2) * sumatoria));
            txtSumatoria.setText(String.format("%,.8f", sumatoria));
        }
    }//GEN-LAST:event_btnTrapzoidalMouseClicked

    private void btnSignoLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoLogActionPerformed
        if(btnSignoLog.isSelected()){
            btnSignoLog.setText("-");
        } else {
            btnSignoLog.setText("+");
        }
        
        txtVarLog.requestFocus();
        txtVarLog.selectAll();
    }//GEN-LAST:event_btnSignoLogActionPerformed

    private void btnCargarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarLogActionPerformed
        if(btnSignoLog.getText().equals("?")){
            JOptionPane.showMessageDialog(null, "Debe indicar un signo (+/-) para la función");
        } else {
            String signo = (btnSignoLog.isSelected())? "-" : "+";
            txtFx.setText("Log(x" + signo + txtVarLog.getText() + ")");
            this.oper = 2;
        }
    }//GEN-LAST:event_btnCargarLogActionPerformed

    private void btnRaiz1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRaiz1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRaiz1MouseDragged

    private void btnRaiz1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRaiz1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRaiz1MouseClicked

    private void btnSignoLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoLnActionPerformed
        if(btnSignoLn.isSelected()){
            btnSignoLn.setText("-");
        } else {
            btnSignoLn.setText("+");
        }
        
        txtVarLn.requestFocus();
        txtVarLn.selectAll();
    }//GEN-LAST:event_btnSignoLnActionPerformed

    private void btnCargarLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarLnActionPerformed
        if(btnSignoLn.getText().equals("?")){
            JOptionPane.showMessageDialog(null, "Debe indicar un signo (+/-) para la función");
        } else {
            String signo = (btnSignoLn.isSelected())? "-" : "+";
            txtFx.setText("Ln(x" + signo + txtVarLn.getText() + ")");
            this.oper = 3;
        }
    }//GEN-LAST:event_btnCargarLnActionPerformed

    private void btnLnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLnMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLnMouseDragged

    private void btnLnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLnMouseClicked

    private void btnCargarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarExpActionPerformed
        txtFx.setText(txtVarExp.getText() + "^x");
        this.oper = 4;
    }//GEN-LAST:event_btnCargarExpActionPerformed

    private void btnExpMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExpMouseDragged

    private void btnExpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExpMouseClicked

    private void btnSimpsonAbtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpsonAbtoMouseClicked
        if(txtA.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite interior");
            txtA.requestFocus();;
            txtA.selectAll();
        } else if(txtB.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite superior");
            txtB.requestFocus();;
            txtB.selectAll();
        } else if(txtN.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor par (n)");
            txtN.requestFocus();;
            txtN.selectAll();
        } else if(txtFx.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe seleccionar y cargar una función (vea la barra superior");
        } else if(Integer.parseInt(txtN.getText()) % 2 != 0){
            JOptionPane.showMessageDialog(null, "El valor de (n) debe ser par");
            txtN.requestFocus();;
            txtN.selectAll();
        } else {
        
            float delta = (Float.parseFloat(txtB.getText()) - Float.parseFloat(txtA.getText())) / Float.parseFloat(txtN.getText());
            lblMetodo.setText("Simpson Abierto");
            lblDelta.setText("Δ = " + String.format("%,.2f", delta));
            String signo;

            setModelo(txtFx.getText());

            int n = Integer.parseInt(txtN.getText()) + 1;
            float x = Float.parseFloat(txtA.getText());
            double res = 0;
            float k = 0;
            double sumatoria = 0;
            String fx = "";
            String coef = "";

            System.out.println("Operacion: " + this.oper);

            for(int i=1; i<=n; i++){
                coef = "";

                switch(this.oper){
                    case 1:
                        signo = (btnSignoRaiz.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarRaiz.getText());
                        res = (signo.equals("+"))? Math.sqrt(x + k) : Math.sqrt(x - k);
                        fx = "√(" + String.format("%,.2f", x) + btnSignoRaiz.getText() + txtVarRaiz.getText() + ")";
                        break;

                    case 2:
                        signo = (btnSignoLog.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLog.getText());
                        res = (signo.equals("+"))? Math.log10(x + k) : Math.log10(x - k);
                        fx = "Log(" + String.format("%,.2f", x) + btnSignoLog.getText() + txtVarLog.getText() + ")";
                        break;

                    case 3:
                        signo = (btnSignoLn.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLn.getText());
                        res = (signo.equals("+"))? Math.log(x + k) : Math.log(x - k);
                        fx = "Ln(" + String.format("%,.2f", x) + btnSignoLn.getText() + txtVarLn.getText() + ")";
                        break;

                    case 4:
                        k = Float.parseFloat(txtVarExp.getText());
                        res = Math.pow(k, x);
                        fx = txtVarExp.getText() + "^" + String.format("%,.2f", x);
                        break;
                }
                
                if(Double.isNaN(res) || Double.isInfinite(res)) res = 0;

                if(i != 1 && i != n) {
                    if(i % 2 == 0){
                        res *= 4;
                        coef = "(4) ";
                    } else {
                        res *= 2;
                        coef = "(2) ";
                    }
                }

                fx = coef + fx;

                setParticion(i, String.format("%,.2f", x), fx, String.format("%,.8f", res));

                sumatoria += res;
                System.out.println("X: " + x + " Res: " + res);
                x += delta;
            }

            System.out.println("Sumatoria: " + sumatoria);
            lblArea.setText(String.format("%,.8f", (delta / 3) * sumatoria));
            txtSumatoria.setText(String.format("%,.8f", sumatoria));
        }
    }//GEN-LAST:event_btnSimpsonAbtoMouseClicked

    private void btnGraficaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficaMouseEntered
    }//GEN-LAST:event_btnGraficaMouseEntered

    private void btnGraficaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficaMouseExited
    }//GEN-LAST:event_btnGraficaMouseExited

    private void txtVarExpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVarExpFocusGained
        txtVarExp.selectAll();
    }//GEN-LAST:event_txtVarExpFocusGained

    private void btnBooleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBooleMouseClicked
        txtN.setText("4");
        
        if(txtA.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite interior");
            txtA.requestFocus();;
            txtA.selectAll();
        } else if(txtB.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite superior");
            txtB.requestFocus();;
            txtB.selectAll();
        } else if(txtN.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor par (n)");
            txtN.requestFocus();;
            txtN.selectAll();
        } else if(txtFx.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe seleccionar y cargar una función (vea la barra superior");
        } else {
            float delta = (Float.parseFloat(txtB.getText()) - Float.parseFloat(txtA.getText())) / 4;
            lblMetodo.setText("Gorge Boole");
            lblDelta.setText("Δ = " + String.format("%,.2f", delta));
            String signo;

            setModelo(txtFx.getText());

            int n = Integer.parseInt(txtN.getText()) + 1;
            float x = Float.parseFloat(txtA.getText());
            double res = 0;
            float k = 0;
            double sumatoria = 0;
            String fx = "";
            String coef = "";

            System.out.println("Operacion: " + this.oper);

            for(int i=1; i<=n; i++){
                coef = "";

                switch(this.oper){
                    case 1:
                        signo = (btnSignoRaiz.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarRaiz.getText());
                        res = (signo.equals("+"))? Math.sqrt(x + k) : Math.sqrt(x - k);
                        fx = "√(" + String.format("%,.2f", x) + btnSignoRaiz.getText() + txtVarRaiz.getText() + ")";
                        break;

                    case 2:
                        signo = (btnSignoLog.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLog.getText());
                        res = (signo.equals("+"))? Math.log10(x + k) : Math.log10(x - k);
                        fx = "Log(" + String.format("%,.2f", x) + btnSignoLog.getText() + txtVarLog.getText() + ")";
                        break;

                    case 3:
                        signo = (btnSignoLn.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLn.getText());
                        res = (signo.equals("+"))? Math.log(x + k) : Math.log(x - k);
                        fx = "Ln(" + String.format("%,.2f", x) + btnSignoLn.getText() + txtVarLn.getText() + ")";
                        break;

                    case 4:
                        k = Float.parseFloat(txtVarExp.getText());
                        res = Math.pow(k, x);
                        fx = txtVarExp.getText() + "^" + String.format("%,.2f", x);
                        break;
                }
                
                if(Double.isNaN(res) || Double.isInfinite(res)) res = 0;

                switch(i) {
                    case 1:
                    case 5:
                        res *= 7; coef = "(7) ";
                        break;
                    case 2:
                    case 4:
                        res *= 32; coef = "(32) ";
                        break;
                    case 3:
                        res *= 12; coef = "(12) ";
                        break;
                }

                fx = coef + fx;

                setParticion(i, String.format("%,.2f", x), fx, String.format("%,.8f", res));

                sumatoria += res;
                System.out.println("X: " + x + " Res: " + res);
                x += delta;
            }

            System.out.println("Sumatoria: " + sumatoria);
            lblArea.setText(String.format("%,.8f", (2 * delta / 45) * sumatoria));
            txtSumatoria.setText(String.format("%,.8f", sumatoria));
        }
    }//GEN-LAST:event_btnBooleMouseClicked

    private void btnSimpson3_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpson3_8MouseClicked
        txtN.setText("3");
        
        if(txtA.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite interior");
            txtA.requestFocus();;
            txtA.selectAll();
        } else if(txtB.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite superior");
            txtB.requestFocus();;
            txtB.selectAll();
        } else if(txtN.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor par (n)");
            txtN.requestFocus();;
            txtN.selectAll();
        } else if(txtFx.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe seleccionar y cargar una función (vea la barra superior");
        } else {
            float delta = (Float.parseFloat(txtB.getText()) - Float.parseFloat(txtA.getText())) / 3;
            lblMetodo.setText("T. Simpson 3/8");
            lblDelta.setText("Δ = " + String.format("%,.2f", delta));
            String signo;

            setModelo(txtFx.getText());

            int n = Integer.parseInt(txtN.getText()) + 1;
            float x = Float.parseFloat(txtA.getText());
            double res = 0;
            float k = 0;
            double sumatoria = 0;
            String fx = "";
            String coef = "";

            System.out.println("Operacion: " + this.oper);

            for(int i=1; i<=n; i++){
                coef = "";

                switch(this.oper){
                    case 1:
                        signo = (btnSignoRaiz.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarRaiz.getText());
                        res = (signo.equals("+"))? Math.sqrt(x + k) : Math.sqrt(x - k);
                        fx = "√(" + String.format("%,.2f", x) + btnSignoRaiz.getText() + txtVarRaiz.getText() + ")";
                        break;

                    case 2:
                        signo = (btnSignoLog.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLog.getText());
                        res = (signo.equals("+"))? Math.log10(x + k) : Math.log10(x - k);
                        fx = "Log(" + String.format("%,.2f", x) + btnSignoLog.getText() + txtVarLog.getText() + ")";
                        break;

                    case 3:
                        signo = (btnSignoLn.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLn.getText());
                        res = (signo.equals("+"))? Math.log(x + k) : Math.log(x - k);
                        fx = "Ln(" + String.format("%,.2f", x) + btnSignoLn.getText() + txtVarLn.getText() + ")";
                        break;

                    case 4:
                        k = Float.parseFloat(txtVarExp.getText());
                        res = Math.pow(k, x);
                        fx = txtVarExp.getText() + "^" + String.format("%,.2f", x);
                        break;
                }
                
                if(Double.isNaN(res) || Double.isInfinite(res)) res = 0;

                if(i != 1 && i != 4){
                    res *= 3; 
                    coef = "(3) ";
                }

                fx = coef + fx;

                setParticion(i, String.format("%,.2f", x), fx, String.format("%,.8f", res));

                sumatoria += res;
                System.out.println("X: " + x + " Res: " + res);
                x += delta;
            }

            System.out.println("Sumatoria: " + sumatoria);
            lblArea.setText(String.format("%,.8f", (3 * delta / 8) * sumatoria));
            txtSumatoria.setText(String.format("%,.8f", sumatoria));
        }
    }//GEN-LAST:event_btnSimpson3_8MouseClicked

    private void btnSimpson1_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpson1_3MouseClicked
        txtN.setText("2");
        
        if(txtA.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite interior");
            txtA.requestFocus();;
            txtA.selectAll();
        } else if(txtB.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor para el límite superior");
            txtB.requestFocus();;
            txtB.selectAll();
        } else if(txtN.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe indicar un valor par (n)");
            txtN.requestFocus();;
            txtN.selectAll();
        } else if(txtFx.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe seleccionar y cargar una función (vea la barra superior");
        } else {
            float delta = (Float.parseFloat(txtB.getText()) - Float.parseFloat(txtA.getText())) / 2;
            lblMetodo.setText("T. Simpson 1/3");
            lblDelta.setText("Δ = " + String.format("%,.2f", delta));
            String signo;

            setModelo(txtFx.getText());

            //int n = ((int) ((Integer.parseInt(txtB.getText()) - Integer.parseInt(txtA.getText())) / delta)) + 1;
            int n = Integer.parseInt(txtN.getText()) + 1;
            float x = Float.parseFloat(txtA.getText());
            double res = 0;
            float k = 0;
            double sumatoria = 0;
            String fx = "";
            String coef = "";

            System.out.println("Operacion: " + this.oper);

            for(int i=1; i<=n; i++){
                coef = "";

                switch(this.oper){
                    case 1:
                        signo = (btnSignoRaiz.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarRaiz.getText());
                        res = (signo.equals("+"))? Math.sqrt(x + k) : Math.sqrt(x - k);
                        fx = "√(" + String.format("%,.2f", x) + btnSignoRaiz.getText() + txtVarRaiz.getText() + ")";
                        break;

                    case 2:
                        signo = (btnSignoLog.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLog.getText());
                        res = (signo.equals("+"))? Math.log10(x + k) : Math.log10(x - k);
                        fx = "Log(" + String.format("%,.2f", x) + btnSignoLog.getText() + txtVarLog.getText() + ")";
                        break;

                    case 3:
                        signo = (btnSignoLn.isSelected())? "-" : "+";
                        k = Float.parseFloat(txtVarLn.getText());
                        res = (signo.equals("+"))? Math.log(x + k) : Math.log(x - k);
                        fx = "Ln(" + String.format("%,.2f", x) + btnSignoLn.getText() + txtVarLn.getText() + ")";
                        break;

                    case 4:
                        k = Float.parseFloat(txtVarExp.getText());
                        res = Math.pow(k, x);
                        fx = txtVarExp.getText() + "^" + String.format("%,.2f", x);
                        break;
                }
                
                if(Double.isNaN(res) || Double.isInfinite(res)) res = 0;

                if(i != 1 && i != 3){
                    res *= 4; 
                    coef = "(4) ";
                }

                fx = coef + fx;

                setParticion(i, String.format("%,.2f", x), fx, String.format("%,.8f", res));

                sumatoria += res;
                System.out.println("X: " + x + " Res: " + res);
                x += delta;
            }

            System.out.println("Sumatoria: " + sumatoria);
            lblArea.setText(String.format("%,.8f", (delta / 3) * sumatoria));
            txtSumatoria.setText(String.format("%,.8f", sumatoria));
        }
    }//GEN-LAST:event_btnSimpson1_3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnBoole;
    private javax.swing.JButton btnCargarExp;
    private javax.swing.JButton btnCargarLn;
    private javax.swing.JButton btnCargarLog;
    private javax.swing.JButton btnCargarRaiz;
    private javax.swing.JPanel btnExp;
    private javax.swing.JLabel btnGrafica;
    private javax.swing.JPanel btnLn;
    private javax.swing.JPanel btnRaiz;
    private javax.swing.JPanel btnRaiz1;
    private javax.swing.JToggleButton btnSignoLn;
    private javax.swing.JToggleButton btnSignoLog;
    private javax.swing.JToggleButton btnSignoRaiz;
    private javax.swing.JPanel btnSimpson1_3;
    private javax.swing.JPanel btnSimpson3_8;
    private javax.swing.JPanel btnSimpsonAbto;
    private javax.swing.JPanel btnTrapzoidal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDelta;
    private javax.swing.JLabel lblDelta1;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JTable tblParticiones;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtFx;
    private javax.swing.JTextArea txtInstrucciones;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtSumatoria;
    private javax.swing.JTextField txtVarExp;
    private javax.swing.JTextField txtVarLn;
    private javax.swing.JTextField txtVarLog;
    private javax.swing.JTextField txtVarRaiz;
    // End of variables declaration//GEN-END:variables
}
